name: an치lisis de calidad de c칩digo

on: push

jobs:
  code_quality_analysis:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
    - name: checkout del codigo
      uses: actions/checkout@v2

    - name: ejecutar an치lisis del c칩digo
      uses: advanced-security/python-lint-code-scanning-action@v1
      with:
        linter: pylint

    - name: comprobar resultado
      run: echo "analisis completado"
